index:
    path: /
    controller: App\Controller\BookController::index

book:
  path: /book/{id}
  controller: App\Controller\BookController::showBookDetails

genre:
  path: /genre/{genre}
  controller: App\Controller\BookController::showBooksInGenre

load:
  path: /load
  controller: App\Controller\BookController::loadMore

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"
